server:
  port: 8086
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: dev
  application:
    name: spring-boot-redis-example
  sql:
    init:
      enabled: false
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
springdoc:
  swagger-ui.tagsSorter: alpha
  writer-with-order-by-keys: true

# http://localhost:8086/api/v1/swagger-ui/index.html
